title: Bits and Pieces
description: Hans Christian Rudolph writing about Functional Programming and Cyber Security

url: https://hcrudolph.com
baseurl: ""

lang: "de-DE"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, i18n, jekyll-twitter-plugin]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   xing: HansChristian_Rudolph2
   linkedin: hcrudolph
   github: hcrudolph
   twitter: hcrudolph
   email: blog@hcr.email

